/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PDFResource {
    id: bigint;
    title: string;
    subject: Category;
    description: string;
    fileName: string;
    timestamp: Time;
}
export interface FAQ {
    question: string;
    answer: string;
}
export type Time = bigint;
export interface SupportMessage {
    subject: string;
    name: string;
    email: string;
    message: string;
}
export interface Course {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    instructor: string;
    description: string;
    category: Category;
    videoUrl: string;
}
export enum Category {
    logicalReasoning = "logicalReasoning",
    generalStudies = "generalStudies",
    math = "math",
    computer = "computer",
    english = "english"
}
export interface backendInterface {
    addCourse(title: string, category: Category, description: string, instructor: string, videoUrl: string, thumbnailUrl: string): Promise<bigint>;
    addFAQ(question: string, answer: string): Promise<void>;
    addPDF(title: string, subject: Category, description: string, fileName: string): Promise<void>;
    deletePDF(id: bigint): Promise<boolean>;
    getAllCourses(): Promise<Array<Course>>;
    getAllPDFs(): Promise<Array<PDFResource>>;
    getCourse(id: bigint): Promise<Course | null>;
    getCoursesByCategory(category: Category): Promise<Array<Course>>;
    getCoursesByInstructor(instructor: string): Promise<Array<Course>>;
    getCoursesByTitle(title: string): Promise<Array<Course>>;
    getFAQs(): Promise<Array<FAQ>>;
    getPDFsBySubject(subject: Category): Promise<Array<PDFResource>>;
    getSupportMessages(): Promise<Array<SupportMessage>>;
    submitSupportMessage(name: string, email: string, subject: string, message: string): Promise<void>;
}
import type { Category as _Category, Course as _Course, PDFResource as _PDFResource, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCourse(arg0: string, arg1: Category, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addFAQ(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0, arg1);
            return result;
        }
    }
    async addPDF(arg0: string, arg1: Category, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPDF(arg0, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPDF(arg0, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deletePDF(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePDF(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePDF(arg0);
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPDFs(): Promise<Array<PDFResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPDFs();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPDFs();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: bigint): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByCategory(arg0: Category): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByInstructor(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByInstructor(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByInstructor(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByTitle(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByTitle(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByTitle(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQs();
            return result;
        }
    }
    async getPDFsBySubject(arg0: Category): Promise<Array<PDFResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPDFsBySubject(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPDFsBySubject(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupportMessages(): Promise<Array<SupportMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportMessages();
            return result;
        }
    }
    async submitSupportMessage(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PDFResource_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PDFResource): PDFResource {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    subject: _Category;
    description: string;
    fileName: string;
    timestamp: _Time;
}): {
    id: bigint;
    title: string;
    subject: Category;
    description: string;
    fileName: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        title: value.title,
        subject: from_candid_Category_n6(_uploadFile, _downloadFile, value.subject),
        description: value.description,
        fileName: value.fileName,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    instructor: string;
    description: string;
    category: _Category;
    videoUrl: string;
}): {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    instructor: string;
    description: string;
    category: Category;
    videoUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: value.thumbnailUrl,
        instructor: value.instructor,
        description: value.description,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        videoUrl: value.videoUrl
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logicalReasoning: null;
} | {
    generalStudies: null;
} | {
    math: null;
} | {
    computer: null;
} | {
    english: null;
}): Category {
    return "logicalReasoning" in value ? Category.logicalReasoning : "generalStudies" in value ? Category.generalStudies : "math" in value ? Category.math : "computer" in value ? Category.computer : "english" in value ? Category.english : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PDFResource>): Array<PDFResource> {
    return value.map((x)=>from_candid_PDFResource_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    logicalReasoning: null;
} | {
    generalStudies: null;
} | {
    math: null;
} | {
    computer: null;
} | {
    english: null;
} {
    return value == Category.logicalReasoning ? {
        logicalReasoning: null
    } : value == Category.generalStudies ? {
        generalStudies: null
    } : value == Category.math ? {
        math: null
    } : value == Category.computer ? {
        computer: null
    } : value == Category.english ? {
        english: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
