/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'logicalReasoning' : null } |
  { 'generalStudies' : null } |
  { 'math' : null } |
  { 'computer' : null } |
  { 'english' : null };
export interface Course {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'instructor' : string,
  'description' : string,
  'category' : Category,
  'videoUrl' : string,
}
export interface FAQ { 'question' : string, 'answer' : string }
export interface PDFResource {
  'id' : bigint,
  'title' : string,
  'subject' : Category,
  'description' : string,
  'fileName' : string,
  'timestamp' : Time,
}
export interface SupportMessage {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addCourse' : ActorMethod<
    [string, Category, string, string, string, string],
    bigint
  >,
  'addFAQ' : ActorMethod<[string, string], undefined>,
  'addPDF' : ActorMethod<[string, Category, string, string], undefined>,
  'deletePDF' : ActorMethod<[bigint], boolean>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllPDFs' : ActorMethod<[], Array<PDFResource>>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getCoursesByCategory' : ActorMethod<[Category], Array<Course>>,
  'getCoursesByInstructor' : ActorMethod<[string], Array<Course>>,
  'getCoursesByTitle' : ActorMethod<[string], Array<Course>>,
  'getFAQs' : ActorMethod<[], Array<FAQ>>,
  'getPDFsBySubject' : ActorMethod<[Category], Array<PDFResource>>,
  'getSupportMessages' : ActorMethod<[], Array<SupportMessage>>,
  'submitSupportMessage' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];