/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'logicalReasoning' : IDL.Null,
  'generalStudies' : IDL.Null,
  'math' : IDL.Null,
  'computer' : IDL.Null,
  'english' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'videoUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const PDFResource = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : Category,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'timestamp' : Time,
});
export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const SupportMessage = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCourse' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPDF' : IDL.Func([IDL.Text, Category, IDL.Text, IDL.Text], [], []),
  'deletePDF' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllPDFs' : IDL.Func([], [IDL.Vec(PDFResource)], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCoursesByCategory' : IDL.Func([Category], [IDL.Vec(Course)], ['query']),
  'getCoursesByInstructor' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getCoursesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getPDFsBySubject' : IDL.Func([Category], [IDL.Vec(PDFResource)], ['query']),
  'getSupportMessages' : IDL.Func([], [IDL.Vec(SupportMessage)], ['query']),
  'submitSupportMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'logicalReasoning' : IDL.Null,
    'generalStudies' : IDL.Null,
    'math' : IDL.Null,
    'computer' : IDL.Null,
    'english' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'videoUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const PDFResource = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : Category,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'timestamp' : Time,
  });
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const SupportMessage = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addCourse' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPDF' : IDL.Func([IDL.Text, Category, IDL.Text, IDL.Text], [], []),
    'deletePDF' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllPDFs' : IDL.Func([], [IDL.Vec(PDFResource)], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCoursesByCategory' : IDL.Func([Category], [IDL.Vec(Course)], ['query']),
    'getCoursesByInstructor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getCoursesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getPDFsBySubject' : IDL.Func(
        [Category],
        [IDL.Vec(PDFResource)],
        ['query'],
      ),
    'getSupportMessages' : IDL.Func([], [IDL.Vec(SupportMessage)], ['query']),
    'submitSupportMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };